name: Sanil Daily KRX (1y, 18:10 KST, skip holidays)

on:
  schedule:
    - cron: "10 9 * * 1-5"   # 09:10 UTC → 18:10 KST (Mon-Fri)
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # === 휴장일/거래없음 사전 체크 ===
      - name: Precheck trading day
        id: precheck
        env:
          TICKER: "062040"
        run: |
          python -m src.precheck_trading_day

      # === 거래일에만 1년치 CSV 2종 생성 ===
      - name: Build latest_trading_volume.csv
        if: steps.precheck.outputs.is_trading_day == 'true'
        env:
          TICKER: "062040"
          OUTPUT_DIR: "data"
          INCLUDE_ETC_CORP: "0"
        run: |
          python -m src.run_trading_volume

      - name: Build latest_market_ohlcv.csv
        if: steps.precheck.outputs.is_trading_day == 'true'
        env:
          TICKER: "062040"
          OUTPUT_DIR: "data"
        run: |
          python -m src.run_market_ohlcv

      # === 고정 URL 확보(권장): data/*.csv 커밋 ===
      - name: Commit CSV to repo
        if: steps.precheck.outputs.is_trading_day == 'true'
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add data/latest_trading_volume.csv data/latest_market_ohlcv.csv
            git commit -m "update latest CSVs $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push
          fi
