name: Sanil Daily KRX (1y, 18:10 KST, skip holidays)

on:
  schedule:
    - cron: "10 9 * * 1-5"   # 09:10 UTC = 18:10 KST (Mon-Fri)
  workflow_dispatch:
    inputs:
      force:
        description: "Run even if today is NOT a trading day"
        required: false
        default: "false"
      use_prev_trading_day:
        description: "When not trading day, use previous trading day"
        required: false
        default: "false"

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 휴장일/거래없음 체크
      - name: Precheck trading day
        id: precheck
        env:
          TICKER: "062040"
        run: |
          python -m src.precheck_trading_day

      # 실행 결정 로직: force == true 이면 실행
      - name: Decide run
        id: decide
        run: |
          FORCE="${{ github.event.inputs.force }}"
          PREV="${{ github.event.inputs.use_prev_trading_day }}"
          IS_TRADE="${{ steps.precheck.outputs.is_trading_day }}"
          echo "force=${FORCE}"
          echo "use_prev_trading_day=${PREV}"
          echo "is_trading_day=${IS_TRADE}"
          if [ "${FORCE}" = "true" ]; then
            echo "do_run=true" >> "$GITHUB_OUTPUT"
            echo "use_prev=false" >> "$GITHUB_OUTPUT"
          else
            if [ "${IS_TRADE}" = "true" ]; then
              echo "do_run=true" >> "$GITHUB_OUTPUT"
              echo "use_prev=false" >> "$GITHUB_OUTPUT"
            else
              if [ "${PREV}" = "true" ]; then
                echo "do_run=true" >> "$GITHUB_OUTPUT"
                echo "use_prev=true" >> "$GITHUB_OUTPUT"
              else
                echo "do_run=false" >> "$GITHUB_OUTPUT"
                echo "use_prev=false" >> "$GITHUB_OUTPUT"
              fi
            fi
          fi

      # 전 영업일 모드일 때 사용할 환경변수(옵션) 처리
      - name: Run latest_trading_volume.csv
        if: steps.decide.outputs.do_run == 'true'
        env:
          TICKER: "062040"
          OUTPUT_DIR: "data"
          INCLUDE_ETC_CORP: "0"
          USE_PREV_TRADING_DAY: "${{ steps.decide.outputs.use_prev }}"
        run: |
          python -m src.run_trading_volume

      - name: Run latest_market_ohlcv.csv
        if: steps.decide.outputs.do_run == 'true'
        env:
          TICKER: "062040"
          OUTPUT_DIR: "data"
          USE_PREV_TRADING_DAY: "${{ steps.decide.outputs.use_prev }}"
        run: |
          python -m src.run_market_ohlcv

      - name: Commit CSV to repo
        if: steps.decide.outputs.do_run == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "update latest CSVs $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push
          else
            echo "No changes to commit."
          fi
